name: photos
description: ente photos application

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 0.0.20+20

environment:
  sdk: ">=2.2.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0
  photo_manager:
    path: thirdparty/flutter_photo_manager
  provider: ^3.1.0
  sqflite: ^1.3.0
  sqflite_migration: ^0.2.0
  path_provider: ^1.6.5
  shared_preferences: ^0.5.6
  dio: ^3.0.9
  image: ^2.1.4
  share: ^0.6.5+4
  draggable_scrollbar: ^0.0.4
  photo_view: ^0.9.2
  visibility_detector: ^0.1.5
  event_bus: ^1.1.1
  sentry: ">=3.0.0 <4.0.0"
  super_logging:
    path: thirdparty/super_logging
  archive: ^2.0.11
  flutter_email_sender: ^3.0.1
  like_button: ^0.2.0
  logging: ^0.11.4
  flutter_image_compress:
    path: thirdparty/flutter_image_compress
  flutter_typeahead: ^1.8.1
  fluttertoast: ^7.1.5
  video_player: ^0.10.11+1
  chewie: ^0.9.10
  cached_network_image: ^2.3.0-beta
  progress_dialog: ^1.2.4
  animate_do: ^1.7.2
  flutter_cache_manager: ^1.4.1
  computer: ^1.0.2
  flutter_secure_storage: ^3.3.3
  uni_links: ^0.4.0
  crisp: ^0.1.3
  flutter_sodium: ^0.1.8
  pedantic: ^1.9.2
  page_transition: "^1.1.7+2"
  convex_bottom_bar: ^2.6.0
  scrollable_positioned_list: ^0.1.8
  connectivity: ^2.0.1
  pretty_dio_logger: ^1.1.1
  url_launcher: ^5.7.10
  fluttercontactpicker: ^3.1.0
  in_app_purchase: ^0.3.5+1
  expansion_card: ^0.1.0
  flutter_password_strength: ^0.1.4
  flutter_inappwebview: ^4.0.0+4
  background_fetch: ^0.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: "0.8.0"

flutter_icons:
  android: true
  image_path_android: "assets/android_icon.png"
  ios: true
  image_path_ios: "assets/ios_icon.png"

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  assets:
    - assets/
  fonts:
  - family: NunitoSans
    fonts:
      - asset: fonts/NunitoSans-Regular.ttf
      - asset: fonts/NunitoSans-Bold.ttf
  - family: Ubuntu
    fonts:
      - asset: fonts/Ubuntu-Regular.ttf
      - asset: fonts/Ubuntu-Light.ttf
  - family: Montserrat
    fonts:
      - asset: fonts/Montserrat-Medium.ttf

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
