display_name: Auth
package_name: auth
maintainer:
  name: Ente.io Developers
  email: human@ente.io
licenses:
  - GPLv3
icon: assets/icons/auth-icon.png
installed_size: 36000

metainfo: linux/packaging/ente_auth.appdata.xml

dependencies:
  - c-ares
  - ffmpeg
  - gtk3
  - http-parser
  - libevent
  - libvpx
  - libxslt
  - libxss
  - minizip
  - nss
  - re2
  - snappy
  - libnotify
  - libappindicator-gtk3

keywords:
  - Authentication
  - 2FA

generic_name: Ente Authentication

categories:
  - Utility

supported_mime_type:
  - x-scheme-handler/enteauth

postinstall_scripts:
  - gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
  - update-desktop-database -q
  - if [ ! -e /usr/lib/libsodium.so.23 ]; then
  - "   ln -s /usr/lib/libsodium.so /usr/lib/libsodium.so.23"
  - fi

postupgrade_scripts:
  - post_install
  
postremove_scripts:
  - gtk-update-icon-cache -q -t -f usr/share/icons/hicolor
  - update-desktop-database -q
  - if [ -e /usr/lib/libsodium.so.23 ]; then
  -   rm /usr/lib/libsodium.so.23
  - fi

startup_notify: false