display_name: Auth
package_name: auth
maintainer:
  name: Ente.io Developers
  email: human@ente.io
priority: optional
section: x11
essential: false
license: GPLv3
icon: assets/icons/auth-icon.png
installed_size: 36000

metainfo: linux/packaging/ente_auth.appdata.xml

dependencies:
  - libwebkit2gtk-4.0-37
  - libsqlite3-0
  - libsodium23
  - libsecret-1-0
  - libappindicator3-1 | libayatana-appindicator3-1
  - gir1.2-appindicator3-0.1 | gir1.2-ayatanaappindicator3-0.1
  - libayatana-ido3-0.4-0

keywords:
  - Authentication
  - 2FA

generic_name: Ente Authentication

categories:
  - Utility

startup_notify: false

supported_mime_type:
  - x-scheme-handler/enteauth
