title: Auth
icon: ../../../assets/generation-icons/icon-macos.png
contents:
  - x: 448
    y: 344
    type: link
    path: "/Applications"
  - x: 192
    y: 344
    type: file
    path: Ente Auth.app
