display_name: Auth
license: GPLv3

icon: assets/icon-light.png

keywords:
  - Authentication
  - 2FA

generic_name: ente Auth

categories:
  - Utility

startup_notify: false

# You can specify the shared libraries that you want to bundle with your app
#
# flutter_distributor automatically detects the shared libraries that your app
# depends on, but you can also specify them manually here.
#
# The following example shows how to bundle the libcurl library with your app.
#
# include:
#   - libcurl.so.4
include:
  - libffi.so.7
