app_id: 9E5F0C93-96A3-4DA9-AE52-1AA6339851FC
publisher: ente.io
publisher_url: https://github.com/ente-io/ente
display_name: ente Auth
create_desktop_icon: true
install_dir_name: enteauth
locales:
  - en
