icon: assets/icons/auth-icon.png
summary: 2FA app with free end-to-end encrypted backup and sync
group: Application/Utility
vendor: Ente.io
packager: Ente.io Developers
packagerEmail: human@ente.io
license: GPLv3
url: https://github.com/ente-io/ente

display_name: Auth

metainfo: linux/packaging/ente_auth.appdata.xml

requires:
  - libsqlite3x
  - webkit2gtk4.0
  - libsodium
  - libsecret
  - libappindicator

keywords:
  - Authentication
  - 2FA

generic_name: Ente Authentication

categories:
  - Utility

startup_notify: false

supported_mime_type:
  - x-scheme-handler/enteauth
