name: locker
description: "Ente Locker â€“ Safe space for your important documents"
publish_to: "none"
version: 0.1.2+9
environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  adaptive_theme: ^3.6.0
  bip39: ^1.0.6
  collection: ^1.18.0
  convert: ^3.1.1
  crypto: ^3.0.6
  dio: ^5.8.0+1
  dots_indicator: ^3.0.0
  dotted_border: ^3.1.0
  email_validator: ^3.0.0
  ente_accounts:
    path: ../../packages/accounts
  ente_base:
    path: ../../packages/base
  ente_configuration:
    path: ../../packages/configuration
  ente_crypto_dart:
    git:
      url: https://github.com/ente-io/ente_crypto_dart.git
  ente_events:
    path: ../../packages/events
  ente_legacy: 
    path: ../../packages/legacy
  ente_lock_screen:
    path: ../../packages/lock_screen
  ente_logging:
    path: ../../packages/logging
  ente_network:
    path: ../../packages/network
  ente_sharing:
    path: ../../packages/sharing
  ente_strings:
    path: ../../packages/strings
  ente_ui:
    path: ../../packages/ui
  ente_utils:
    path: ../../packages/utils
  event_bus: ^2.0.1 
  expandable: ^5.0.1
  fast_base58: ^0.2.1
  file_picker: ^10.2.0
  file_saver: ^0.3.1
  flutter:
    sdk: flutter
  flutter_displaymode: ^0.6.0
  flutter_local_authentication:
    git:
      url: https://github.com/eaceto/flutter_local_authentication
      ref: 1ac346a04592a05fd75acccf2e01fa3c7e955d96
  flutter_localizations:
    sdk: flutter 
  flutter_svg: ^2.2.1
  hugeicons: ^1.1.1
  intl: ^0.20.2
  io: ^1.0.5
  listen_sharing_intent: ^1.9.2
  logging: ^1.3.0
  open_file: ^3.5.10
  package_info_plus: ^8.3.0
  path: ^1.9.0
  path_provider: ^2.1.5
  share_plus: ^11.0.0
  shared_preferences: ^2.5.3
  sqflite: ^2.4.1 
  tray_manager: ^0.5.0
  tuple: ^2.0.2
  url_launcher: ^6.3.2
  uuid: ^4.5.1 
  window_manager: ^0.5.1

dev_dependencies:
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/
    - assets/icons/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.ttf
        - asset: assets/fonts/Inter-Medium.ttf
        - asset: assets/fonts/Inter-Light.ttf
        - asset: assets/fonts/Inter-SemiBold.ttf
        - asset: assets/fonts/Inter-Bold.ttf
    - family: Montserrat
      fonts:
        - asset: assets/fonts/Montserrat-Bold.ttf

flutter_icons:
  adaptive_icon_foreground: "assets/launcher-icons/icon-foreground.png"
  adaptive_icon_background: "#1071ff"
  android: "icon_blue"
  ios: "IconBlue"
  image_path: "assets/launcher-icons/icon-blue.png"
