[package]
name = "llmchat_sync_uniffi"
version = "0.1.0"
edition = "2024"

[lib]
name = "llmchat_sync_uniffi"
crate-type = ["staticlib", "cdylib"]

[dependencies]
llmchat-sync = { path = "../../sync" }
serde = { version = "1", features = ["derive"] }
thiserror = "2"
uniffi = { version = "0.31.0" }

[build-dependencies]
