[package]
name = "inference_rs_uniffi"
version = "0.1.0"
edition = "2024"

[lib]
name = "inference_rs_uniffi"
crate-type = ["staticlib", "cdylib"]

[dependencies]
inference_rs = { path = "../../inference" }
serde = { version = "1", features = ["derive"] }
thiserror = "1"
uniffi = { version = "0.31.0" }
