name: ente_pure_utils
description: The depencies should be maintained by pub.dev/flutter.dev
version: 1.0.0
publish_to: none

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=1.17.0"

dependencies:
  collection: ^1.18.0
  convert: ^3.1.1
  crypto: ^3.0.5
  email_validator: ^3.0.0
  flutter:
    sdk: flutter
  intl: ^0.20.2
  logging: ^1.3.0
  path: ^1.9.0
  path_provider: ^2.1.5

dev_dependencies:
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter

flutter:
