# Sample docker compose file, not meant for production use.

services:
  museum:
    image: ghcr.io/ente-io/server
    ports:
      - 8080:8080 # API
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      ENTE_CREDENTIALS_FILE: /credentials.yaml
    configs:
      - source: credentials_yaml
        target: /credentials.yaml
    volumes:
      - ./museum.yaml:/museum.yaml:ro
      - ./data:/data:ro

  # Resolve "localhost:3200" in the museum container to the minio container.
  socat-museum-3200:
    image: alpine/socat
    network_mode: service:museum
    depends_on: [museum]
    command: "TCP-LISTEN:3200,fork,reuseaddr TCP:minio:3200"

  web:
    image: ghcr.io/ente-io/web
    # Uncomment what you need to tweak.
    ports:
      - 3000:3000 # Photos web app
      # - 3001:3001 # Accounts
      - 3002:3002 # Public albums
      # - 3003:3003 # Auth
      # - 3004:3004 # Cast
    # environment:
    #   ENTE_API_ORIGIN: http://localhost:8080
    #   ENTE_ALBUMS_ORIGIN: https://localhost:3002

  # Resolve "localhost:3200" in the web container to the minio container.
  socat-web-3200:
    image: alpine/socat
    network_mode: service:web
    depends_on: [web]
    command: "TCP-LISTEN:3200,fork,reuseaddr TCP:minio:3200"

  # Resolve "localhost:8080" in the web container to the museum container.
  socat-web-8080:
    image: alpine/socat
    network_mode: service:web
    depends_on: [web]
    command: "TCP-LISTEN:8080,fork,reuseaddr TCP:minio:8080"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: pguser
      POSTGRES_PASSWORD: pgpass
      POSTGRES_DB: ente_db
    healthcheck:
      test: pg_isready -q -d ente_db -U pguser
      start_period: 40s
      start_interval: 1s
    volumes:
      - postgres-data:/var/lib/postgresql/data

  minio:
    image: minio/minio
    ports:
      - 3200:3200 # MinIO API
    environment:
      MINIO_ROOT_USER: changeme
      MINIO_ROOT_PASSWORD: changeme1234
    command: server /data --address ":3200" --console-address ":3201"
    volumes:
      - minio-data:/data
    post_start:
      - command: |
          sh -c '
          #!/bin/sh

          while ! mc config host add h0 http://minio:3200 changeme changeme1234 2>/dev/null
          do
            echo "Waiting for minio..."
            sleep 0.5
          done

          cd /data

          mc mb -p b2-eu-cen
          mc mb -p wasabi-eu-central-2-v3
          mc mb -p scw-eu-fr-v3
          '

configs:
  credentials_yaml:
    content: |
      db:
          host: postgres
          port: 5432
          name: ente_db
          user: pguser
          password: pgpass

      key:
          encryption: yvmG/RnzKrbCb9L3mgsmoxXr9H7i2Z4qlbT0mL3ln4w=
          hash: KXYiG07wC7GIgvCSdg+WmyWdXDAn6XKYJtp/wkEU7x573+byBRAYtpTP0wwvi8i/4l37uicX1dVTUzwH3sLZyw==

      jwt:
          secret: i2DecQmfGreG6q1vBj5tCokhlN41gcfS2cjOs9Po-u8=

      s3:
          are_local_buckets: true
          b2-eu-cen:
              key: changeme
              secret: changeme1234
              endpoint: localhost:3200
              region: eu-central-2
              bucket: b2-eu-cen
          wasabi-eu-central-2-v3:
              key: changeme
              secret: changeme1234
              endpoint: localhost:3200
              region: eu-central-2
              bucket: wasabi-eu-central-2-v3
              compliance: false
          scw-eu-fr-v3:
              key: changeme
              secret: changeme1234
              endpoint: localhost:3200
              region: eu-central-2
              bucket: scw-eu-fr-v3

volumes:
  postgres-data:
  minio-data:
