name: "Push sources to Crowdin (auth)"

on:
    push:
        branches: [main]
        paths:
            # Run workflow when auth's intl_en.arb is changed
            - "auth/lib/l10n/arb/app_en.arb"
            # Or the workflow itself is changed
            - ".github/workflows/auth-crowdin.yml"

jobs:
    push-sources-to-crowdin:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Crowdin's action
              uses: crowdin/github-action@v2
              with:
                  base_path: "auth/"
                  config: "auth/crowdin.yml"
                  upload_sources: true
                  upload_translations: false
                  download_translations: false
                  project_id: 575169
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
