name: "Push sources to Crowdin (locker)"

on:
    push:
        branches: [main]
        paths:
            # Run workflow when locker's app_en.arb is changed
            - "mobile/apps/locker/lib/l10n/app_en.arb"
            # Or the workflow itself is changed
            - ".github/workflows/locker-crowdin-push.yml"

permissions:
    contents: write
    pull-requests: write

jobs:
    push-sources-to-crowdin:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Crowdin's action
              uses: crowdin/github-action@v2
              with:
                  base_path: "mobile/apps/locker/"
                  config: "mobile/apps/locker/crowdin.yml"
                  upload_sources: true
                  upload_translations: false
                  download_translations: false
                  project_id: 860056
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
