name: "Sync Crowdin translations (locker)"

on:
    schedule:
        # Run Mondays at ~7:00 AM IST
        # See: [Note: Run workflow on specific days of the week]
        - cron: "30 1 * * 1"
    # Also allow manually running the workflow.
    workflow_dispatch:

permissions:
    contents: write
    pull-requests: write

jobs:
    synchronize-with-crowdin:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Crowdin's action
              uses: crowdin/github-action@v2
              with:
                  base_path: "mobile/apps/locker/"
                  config: "mobile/apps/locker/crowdin.yml"
                  upload_sources: true
                  upload_translations: false
                  download_translations: true
                  localization_branch_name: translations/locker
                  create_pull_request: true
                  skip_untranslated_strings: true
                  pull_request_title: "[locker] New translations"
                  pull_request_body: "New translations from [Crowdin](https://crowdin.com/project/ente-locker-app)"
                  pull_request_base_branch_name: "main"
                  project_id: 860056
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
