name: "Push sources to Crowdin (mobile)"

on:
    push:
        branches: [main]
        paths:
            # Run workflow when mobiles's intl_en.arb is changed
            - "mobile/lib/l10n/intl_en.arb"
            # Or the workflow itself is changed
            - ".github/workflows/mobile-crowdin.yml"

jobs:
    push-sources-to-crowdin:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Crowdin's action
              uses: crowdin/github-action@v2
              with:
                  base_path: "mobile/"
                  config: "mobile/crowdin.yml"
                  upload_sources: true
                  upload_translations: false
                  download_translations: false
                  project_id: 574741
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
