name: "Sync Crowdin translations (mobile)"

on:
    push:
        branches: [main]
        paths:
            # Run workflow when mobiles's intl_en.arb is changed
            - "mobile/lib/l10n/intl_en.arb"
            # Or the workflow itself is changed
            - ".github/workflows/mobile-crowdin.yml"
    schedule:
        # See: [Note: Run workflow on specific days of the week]
        - cron: "40 1 * * 2,5"
    # Also allow manually running the workflow
    workflow_dispatch:

jobs:
    synchronize-with-crowdin:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Crowdin's action
              uses: crowdin/github-action@v1
              with:
                  base_path: "mobile/"
                  config: "mobile/crowdin.yml"
                  upload_sources: true
                  upload_translations: false
                  download_translations: true
                  localization_branch_name: crowdin-translations-mobile
                  create_pull_request: true
                  skip_untranslated_strings: true
                  pull_request_title: "[mobile] New translations"
                  pull_request_body: "New translations from [Crowdin](https://crowdin.com/project/ente-photos-app)"
                  pull_request_base_branch_name: "main"
                  project_id: 574741
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
