name: Flutter CI

# This workflow is triggered on pushes to the repository.
on:
  workflow_dispatch:
    # Enable manual run
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v4.2.0

jobs:
  build:
    # This job will run on ubuntu virtual machine
    runs-on: ubuntu-latest
    steps:

      # Setup Java environment in order to build the Android app.
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'

      # Setup the flutter environment.
      - uses: subosito/flutter-action@v1
        with:
          channel: 'stable'
          flutter-version: '2.2.3'

      # Fetch sub modules
      - run: git submodule update --init --recursive

      # Get flutter dependencies.
      - run: flutter pub get

      - name: decode keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'keystore/ente_photos_key.jks'
          encodedString: ${{ secrets.SIGNING_KEY }}

      # Build independent apk.
      - name: build apk
        run: flutter build apk --release --flavor independent
        env:
          SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
          SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
          SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}

      # Upload generated apk to the artifacts.
      - uses: actions/upload-artifact@v2
        with:
          name: release-apk
          path: build/app/outputs/apk/release/app-release.apk
