name: "Lint (rust)"

on:
    # Run on every pull request (open or push to it) that changes Rust code
    #
    # See also: rust-lint-cli.yml
    pull_request:
        paths:
            - "rust/core/**"
            - "mobile/packages/rust/rust/**"
            - "mobile/apps/photos/rust/**"
            - "web/packages/wasm/Cargo.*"
            - "web/packages/wasm/src/**"
            - ".github/workflows/rust-lint.yml"

permissions:
    contents: read

# Cancel in-progress lint runs when a new commit is pushed.
concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

env:
    RUSTFLAGS: -D warnings

jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Cache
              uses: actions/cache@v4
              with:
                  path: |
                      ~/.cargo/registry
                      ~/.cargo/git
                      rust/core/target
                      mobile/packages/rust/rust/target
                      mobile/apps/photos/rust/target
                      web/packages/wasm/target
                  # This also hashes cli's Cargo.lock, but it's fine for now.
                  key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}

            - name: Install Flutter Rust Bridge
              run: cargo install flutter_rust_bridge_codegen

            - name: Generate Rust bindings (ente_rust)
              working-directory: mobile/packages/rust
              run: flutter_rust_bridge_codegen generate

            - name: Generate Rust bindings (ente_photos_rust)
              working-directory: mobile/apps/photos
              run: flutter_rust_bridge_codegen generate

            - name: Check formatting (core)
              working-directory: rust/core
              run: cargo fmt --check

            - name: Run clippy (core)
              working-directory: rust/core
              run: cargo clippy --all-targets --all-features

            - name: Build (core)
              working-directory: rust/core
              run: cargo build

            - name: Test (core)
              working-directory: rust/core
              run: cargo test

            - name: Check formatting (ente_rust)
              working-directory: mobile/packages/rust/rust
              run: cargo fmt -- src/frb_generated.rs && cargo fmt --check

            - name: Run clippy (ente_rust)
              working-directory: mobile/packages/rust/rust
              run: cargo clippy --all-targets --all-features

            - name: Build (ente_rust)
              working-directory: mobile/packages/rust/rust
              run: cargo build

            - name: Test (ente_rust)
              working-directory: mobile/packages/rust/rust
              run: cargo test

            - name: Check formatting (ente_photos_rust)
              working-directory: mobile/apps/photos/rust
              run: cargo fmt -- src/frb_generated.rs && cargo fmt --check

            - name: Run clippy (ente_photos_rust)
              working-directory: mobile/apps/photos/rust
              run: cargo clippy --all-targets --all-features

            - name: Build (ente_photos_rust)
              working-directory: mobile/apps/photos/rust
              run: cargo build

            - name: Test (ente_photos_rust)
              working-directory: mobile/apps/photos/rust
              run: cargo test

            - name: Check formatting (wasm)
              working-directory: web/packages/wasm
              run: cargo fmt --check

            - name: Run clippy (wasm)
              working-directory: web/packages/wasm
              run: cargo clippy --all-targets --all-features

            - name: Build (wasm)
              working-directory: web/packages/wasm
              run: cargo build

            - name: Test (wasm)
              working-directory: web/packages/wasm
              run: cargo test
