name: "Deploy preview (web)"

on:
    workflow_dispatch:
        inputs:
            app:
                description: "App to build and deploy"
                type: choice
                required: true
                default: "photos"
                options:
                    - "accounts"
                    - "auth"
                    - "cast"
                    - "payments"
                    - "photos"

permissions:
    contents: read

jobs:
    deploy:
        runs-on: ubuntu-latest

        defaults:
            run:
                working-directory: web

        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Setup node and enable yarn caching
              uses: actions/setup-node@v4
              with:
                  node-version: 20
                  cache: "yarn"
                  cache-dependency-path: "web/yarn.lock"

            - name: Install dependencies
              run: yarn install

            - name: Build ${{ inputs.app }}
              run: yarn build:${{ inputs.app }}

            - name: Publish ${{ inputs.app }} to preview
              uses: cloudflare/wrangler-action@v3
              with:
                  accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
                  apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
                  command: pages deploy --project-name=ente --commit-dirty=true --branch=preview web/apps/${{ inputs.app }}/out
