name: "Publish ghcr (web)"

on:
    # Run automatically every Wednesday, at 07:00 UTC.
    schedule:
        - cron: '0 7 * * 3'
    # Run manually if needed to publish out of schedule.
    workflow_dispatch:

permissions:
    contents: read
    packages: write

jobs:
    publish:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v4

            - name: Build and push
              uses: mr-smithers-excellent/docker-build-push@v6
              with:
                  dockerfile: web/Dockerfile
                  directory: web
                  # Resultant package name will be ghcr.io/ente-io/web
                  image: web
                  registry: ghcr.io
                  enableBuildKit: true
                  multiPlatform: true
                  platform: linux/amd64,linux/arm64
                  tags: ${{ github.sha }}, latest
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Update branch ghcr/web to point to source commit
              run: |
                  git push -f origin HEAD:refs/heads/ghcr/web
