name: "Push Crowdin translations (web)"

# This is a variant of web-crowdin-sync.yml that uploads the translated strings in
# addition to the source strings.
#
# This allows us to change the strings in our source code for an automated
# refactoring (e.g. renaming a key), and then run this workflow to update the
# data in Crowdin taking our source code as the source of truth.

on:
    # Trigger manually, or using
    # `gh workflow run web-crowdin-push-both.yml --ref <my-branch>`
    workflow_dispatch:

jobs:
    push-both-to-crowdin:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Crowdin push
              uses: crowdin/github-action@v2
              with:
                  base_path: "web/"
                  config: "web/crowdin.yml"
                  upload_sources: true
                  upload_translations: true
                  download_translations: false
                  project_id: 569613
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
