name: "Sync Crowdin translations (web)"

on:
    push:
        branches: [main]
        paths:
            # Run workflow when web's en-US/translation.json is changed
            - "web/packages/next/locales/en-US/translation.json"
            # Or the workflow itself is changed
            - ".github/workflows/web-crowdin.yml"
    schedule:
        # [Note: Run workflow on specific days of the week]
        #
        # The last (5th) component of the cron syntax denotes the day of the
        # week, with 0 == SUN and 6 == SAT. So, for example, to run on every TUE
        # and FRI, this can be set to `2,5`.
        #
        # See also: [Note: Run workflow every 24 hours]
        - cron: "20 1 * * 2"
    # Also allow manually running the workflow.
    workflow_dispatch:

jobs:
    synchronize-with-crowdin:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Crowdin's action
              uses: crowdin/github-action@v2
              with:
                  base_path: "web/"
                  config: "web/crowdin.yml"
                  upload_sources: true
                  upload_translations: false
                  download_translations: true
                  localization_branch_name: translations/web
                  create_pull_request: true
                  skip_untranslated_strings: true
                  pull_request_title: "[web] New translations"
                  pull_request_body: "New translations from [Crowdin](https://crowdin.com/project/ente-photos-web)"
                  pull_request_base_branch_name: "main"
                  project_id: 569613
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  CROWDIN_PERSONAL_TOKEN: ${{ secrets.CROWDIN_PERSONAL_TOKEN }}
